"""
Seeding-Script für die "Frage des Tages" Datenbank.
Dieses Script lädt vordefinierte Fragen in die PostgreSQL-Datenbank.
"""

import asyncio
import os
from dotenv import load_dotenv
from database import get_db_connection
from lifecycle import log_success, log_error, log_database_action

# HIER DEINE 365 FRAGEN EINTRAGEN
FDT_QUESTIONS_LIST = [
    "Wenn du dir eine Superkraft aussuchen könntest, welche wäre es und warum?",
    "Welche fiktive Welt aus einem Buch oder Film würdest du am liebsten besuchen?",
    "Was war dein absolutes Lieblings-Kuscheltier als Kind?",
    "Wenn du einen Tag lang unsichtbar wäre, was würdest du tun?",
    "Welches Lied kannst du immer wieder hören, ohne dass es dir langweilig wird?",
    "Was ist das Verrückteste, was du jemals gegessen hast?",
    "Wenn du eine Zeitmaschine hättest, in welche Zeit würdest du reisen?",
    "Was ist dein größter Traum für die Zukunft?",
    "Welcher Disney-Charakter beschreibt deine Persönlichkeit am besten?",
    "Was würdest du tun, wenn du einen Tag lang der reichste Mensch der Welt wärst?",
    "Welches Hobby würdest du gerne lernen?",
    "Was ist das Beste, was dir heute passiert ist?",
    "Wenn du ein Tier für einen Tag sein könntest, welches würdest du wählen?",
    "Was ist deine liebste Kindheitserinnerung?",
    "Welchen Beruf hättest du gerne, wenn Geld keine Rolle spielen würde?",
    "Was ist dein Lieblings-Eis-Geschmack?",
    "Wenn du einen Wunsch frei hättest, was würdest du dir wünschen?",
    "Welche Sprache würdest du gerne fließend sprechen können?",
    "Was ist das Mutigste, was du je getan hast?",
    "Welcher Ort auf der Welt steht ganz oben auf deiner Reiseliste?",
    "Was machst du, um dich zu entspannen?",
    "Welches Buch hat dich am meisten geprägt?",
    "Was ist dein Lieblings-Sprichwort oder Zitat?",
    "Wenn du berühmt werden könntest, wofür würdest du berühmt sein wollen?",
    "Was ist deine größte Angst?",
    "Welchen Rat würdest du deinem 10-jährigen Ich geben?",
    "Was ist dein Lieblings-Comfort-Food?",
    "Wenn du ein Superheld wärst, wie würde dein Kostüm aussehen?",
    "Was ist das Dümmste, was du als Kind geglaubt hast?",
    "Welche drei Dinge würdest du auf eine einsame Insel mitnehmen?",
    "Was ist deine Definition von Glück?",
    "Welcher Film kann dich immer zum Lachen bringen?",
    "Was ist das Ungewöhnlichste an dir?",
    "Wenn du einen Podcast starten würdest, worüber würde er handeln?",
    "Was ist dein Lieblings-Wochentag und warum?",
    "Welches Talent würdest du gerne über Nacht erlernen?",
    "Was ist das Erste, was du denkst, wenn du aufwachst?",
    "Welche Farbe beschreibt deine Stimmung heute?",
    "Was ist dein Lieblings-Emoji und warum?",
    "Wenn du ein Lied über dein Leben schreiben würdest, wie würde der Titel lauten?",
    "Was ist das Beste Geschenk, das du je bekommen hast?",
    "Welchen Namen würdest du deinem Haustier geben, wenn du eins hättest?",
    "Was ist deine liebste Art, Zeit zu verschwenden?",
    "Wenn du ein Geschäft eröffnen könntest, was würdest du verkaufen?",
    "Was ist das Seltsamste, was du in deinem Kühlschrank hast?",
    "Welche schlechte Angewohnheit würdest du gerne loswerden?",
    "Was ist dein Lieblings-Kinderlied?",
    "Wenn du ein Kleidungsstück für den Rest deines Lebens tragen müsstest, was wäre es?",
    "Was ist das Schönste Kompliment, das du je bekommen hast?",
    "Welche App auf deinem Handy nutzt du am meisten?",
    "Was ist dein Lieblings-Wettertyp?",
    "Wenn du einen Tag lang Chef der Welt wärst, was würdest du ändern?",
    "Was ist das Merkwürdigste, was du sammeln würdest?",
    "Welcher Charakter aus einem Videospiel würdest du gerne sein?",
    "Was ist dein Lieblings-Geräusch?",
    "Wenn du eine Warnung auf deiner Stirn tragen müsstest, was würde darauf stehen?",
    "Was ist das Verrückteste, was du dir jemals gekauft hast?",
    "Welche Frage würdest du gerne einem Wahrsager stellen?",
    "Was ist dein Lieblings-Mitternachtssnack?",
    "Wenn du einen Song als deine Lebenshymne auswählen müsstest, welcher wäre es?",
    "Was ist das Beste daran, erwachsen zu sein?",
    "Welcher Geschmack beschreibt deine Persönlichkeit?",
    "Was ist das Coolste, was du in der Natur gesehen hast?",
    "Wenn du einen eigenen Feiertag erfinden könntest, wie würde er heißen?",
    "Was ist dein Lieblings-Küchengerät?",
    "Welche Erinnerung bringt dich immer zum Lächeln?",
    "Was ist das Peinlichste, was dir je passiert ist?",
    "Wenn du ein Buch über dein Leben schreiben würdest, welcher wäre der erste Satz?",
    "Was ist deine liebste Art zu reisen?",
    "Welches Märchen würdest du gerne neu schreiben?",
    "Was ist das Aufregendste, was du dieses Jahr gemacht hast?",
    "Wenn du einen eigenen Planeten haben könntest, wie würde er aussehen?",
    "Was ist dein Lieblings-Ritual am Morgen?",
    "Welcher Duft erinnert dich an deine Kindheit?",
    "Was ist das Verrückteste, was auf deiner Bucket-List steht?",
    "Wenn du einen Tag mit einer historischen Persönlichkeit verbringen könntest, mit wem?",
    "Was ist dein Lieblings-Keksgeschmack?",
    "Welche Superkraft würde dir im Alltag am meisten helfen?",
    "Was ist das Ungewöhnlichste, was du als Hobby ausprobiert hast?",
    "Wenn du einen Zaubertrank brauen könntest, was würde er bewirken?",
    "Was ist dein Lieblings-Wort in einer anderen Sprache?",
    "Welcher Moment hat dich heute zum Lachen gebracht?",
    "Was ist das Mutigste, was du in letzter Zeit getan hast?",
    "Wenn du ein Instrument perfekt spielen könntest, welches wäre es?",
    "Was ist deine liebste Art, andere zum Lächeln zu bringen?",
    "Welcher Raum in deinem Zuhause ist dein Lieblingsplatz?",
    "Was ist das Interessanteste, was du diese Woche gelernt hast?",
    "Wenn du eine Regel für die ganze Welt machen könntest, welche wäre es?",
    "Was ist dein Lieblings-Kindheitsspiel?",
    "Welche Technologie aus Science-Fiction würdest du gerne haben?",
    "Was ist das Schönste, was du heute gesehen hast?",
    "Wenn du einen Monat lang nur eine Art von Essen essen könntest, welche?",
    "Was ist dein Lieblings-Familienfoto und warum?",
    "Welcher Charakter aus einem Buch ist dir am ähnlichsten?",
    "Was ist das Verrückteste Gerücht, das du über dich gehört hast?",
    "Wenn du einen eigenen Themepark haben könntest, was wäre das Hauptthema?",
    "Was ist dein Lieblings-Gute-Nacht-Ritual?",
    "Welche Eigenschaft bewunderst du am meisten bei anderen?",
    "Was ist das Spontanste, was du je getan hast?",
    "Wenn du ein Tattoo bekommen müsstest, was würde es sein?",
    "Was ist dein Lieblings-Kaffee- oder Teegeschmack?",
    "Welcher Tag in deinem Leben würdest du gerne wiederholen?",
    "Was ist das Sinnvollste, was du mit 100 Euro machen könntest?",
    "Wenn du einen eigenen Radiosender hättest, welche Musik würdest du spielen?",
    "Was ist dein Lieblings-Internetmeme?",
    "Welche Fähigkeit deiner Haustiere würdest du gerne haben?",
    "Was ist das Großzügigste, was jemand für dich getan hat?",
    "Wenn du einen perfekten Tag planen könntest, wie würde er aussehen?",
    "Was ist dein Lieblings-Urlaubssouvenir?",
    "Welche Verschwörungstheorie findest du am unterhaltsamsten?",
    "Was ist das Kreativste Geschenk, das du je gemacht hast?",
    "Wenn du einen eigenen Superhelden-Sidekick haben könntest, wie wäre er?",
    "Was ist dein Lieblings-Frühstückscereal?",
    "Welcher Moment in der Geschichte würdest du gerne miterlebt haben?",
    "Was ist das Dümmste, was du aus Langeweile getan hast?",
    "Wenn du einen eigenen YouTube-Kanal starten würdest, was wäre der Inhalt?",
    "Was ist dein Lieblings-Augenblick des Tages?",
    "Welche drei Adjektive beschreiben dich am besten?",
    "Was ist das Verrückteste, was du dir als Kind vorgestellt hast?",
    "Wenn du einen eigenen Cocktail erfinden könntest, wie würde er schmecken?",
    "Was ist dein Lieblings-Platz zum Nachdenken?",
    "Welcher Filmcharakter würdest du gerne in der Realität treffen?",
    "Was ist das Lustigste, was dein Haustier (oder ein Tier) je getan hat?",
    "Wenn du einen eigenen Comic zeichnen könntest, worum würde es gehen?",
    "Was ist dein Lieblings-Winteraktivität?",
    "Welche Tradition würdest du gerne in deiner Familie einführen?",
    "Was ist das Überraschendste, was du über dich selbst gelernt hast?",
    "Wenn du einen eigenen Freizeitpark-Ride entwerfen könntest, wie wäre er?",
    "Was ist dein Lieblings-Sommeraktivität?",
    "Welcher Moment hat dich in letzter Zeit stolz gemacht?",
    "Was ist das Seltsamste, was du in einem Traum erlebt hast?",
    "Wenn du eine eigene TV-Show moderieren könntest, was wäre das Format?",
    "Was ist dein Lieblings-Herbstaktivität?",
    "Welche kleine Freude macht deinen Tag immer besser?",
    "Was ist das Beeindruckendste, was du mit eigenen Händen gemacht hast?",
    "Wenn du einen eigenen Escape Room designen könntest, was wäre das Thema?",
    "Was ist dein Lieblings-Frühlingsaktivität?",
    "Welcher Rat hat dein Leben verändert?",
    "Was ist das Verrückteste, was du als Experiment ausprobiert hast?",
    "Wenn du einen eigenen Pretzelstand haben könntest, welche Geschmacksrichtungen würdest du anbieten?",
    "Was ist deine liebste Art, dich selbst zu belohnen?",
    "Welcher Moment bringt dich immer wieder zum Staunen?",
    "Was ist das Coolste, was du handwerklich kannst?",
    "Wenn du einen eigenen Dokumentarfilm drehen könntest, worüber?",
    "Was ist dein Lieblings-Picknick-Essen?",
    "Welche Erinnerung an die Schule lässt dich schmunzeln?",
    "Was ist das Praktischste, was du je gelernt hast?",
    "Wenn du einen eigenen Kalender mit Fotos machen könntest, was wäre das Thema?",
    "Was ist dein Lieblings-Partyspiel?",
    "Welcher Gedanke hilft dir, wenn du schlecht gelaunt bist?",
    "Was ist das Originellste Geschenk, das du je bekommen hast?",
    "Wenn du einen eigenen Food-Truck haben könntest, was würdest du verkaufen?",
    "Was ist dein Lieblings-Brettspiel?",
    "Welcher Ort in deiner Stadt ist dein Geheimtipp?",
    "Was ist das Hilfreichste, was dir jemand beigebracht hat?",
    "Wenn du einen eigenen Garten haben könntest, was würdest du anpflanzen?",
    "Was ist dein Lieblings-Kartenspiel?",
    "Welcher Moment hat dich emotional am meisten berührt?",
    "Was ist das Ungewöhnlichste, was du in einem Museum gesehen hast?",
    "Wenn du einen eigenen Blog schreiben würdest, welcher wäre der erste Post?",
    "Was ist dein Lieblings-Videospiel?",
    "Welche Fähigkeit möchtest du dieses Jahr noch entwickeln?",
    "Was ist das Faszinierendste, was du über das Weltall weißt?",
    "Wenn du einen eigenen Lehrplan erstellen könntest, was würdest du unterrichten?",
    "Was ist dein Lieblings-Outdoor-Sport?",
    "Welcher Gedanke motiviert dich, morgens aufzustehen?",
    "Was ist das Verwirrendste, was du als Kind nicht verstanden hast?",
    "Wenn du einen eigenen Spa eröffnen könntest, welche Behandlungen würdest du anbieten?",
    "Was ist dein Lieblings-Indoor-Sport?",
    "Welcher Moment hat dich zum Nachdenken gebracht?",
    "Was ist das Verrückteste, was du in einem Antiquitätenladen gefunden hast?",
    "Wenn du einen eigenen Workshop anbieten könntest, was würdest du lehren?",
    "Was ist dein Lieblings-Teamspiel?",
    "Welche Geschichte aus deiner Kindheit erzählst du am liebsten?",
    "Was ist das Magischste, was du in der Natur beobachtet hast?",
    "Wenn du einen eigenen Laden für Sammlerobjekte haben könntest, was würdest du verkaufen?",
    "Was ist dein Lieblings-Einzelsport?",
    "Welcher Moment hat dich dankbar gemacht?",
    "Was ist das Süßeste, was ein Kind zu dir gesagt hat?",
    "Wenn du einen eigenen Vergnügungspark haben könntest, welches wäre die Hauptattraktion?",
    "Was ist dein Lieblings-Wassersport?",
    "Welche Lektion hast du auf die harte Tour gelernt?",
    "Was ist das Entspannendste, was du je gemacht hast?",
    "Wenn du einen eigenen Zirkus haben könntest, welche Acts würdest du zeigen?",
    "Was ist dein Lieblings-Wintersport?",
    "Welcher Augenblick hat dich überrascht?",
    "Was ist das Kreativste, was du aus Langeweile erschaffen hast?",
    "Wenn du einen eigenen Bauernhof haben könntest, welche Tiere würdest du halten?",
    "Was ist dein Lieblings-Campingaktivität?",
    "Welcher Rat würdest du jemandem geben, der sich verloren fühlt?",
    "Was ist das Friedlichste, was du je erlebt hast?",
    "Wenn du einen eigenen Musikclub eröffnen könntest, welche Musik würdest du spielen?",
    "Was ist dein Lieblings-Regentag-Aktivität?",
    "Welcher Gedanke tröstet dich, wenn du traurig bist?",
    "Was ist das Aufregendste Abenteuer, das du je erlebt hast?",
    "Wenn du einen eigenen Buchclub gründen könntest, welches erste Buch würdest du wählen?",
    "Was ist dein Lieblings-Familienspiel?",
    "Welche Eigenschaft an dir hat sich am meisten verändert?",
    "Was ist das Herzerwärmendste, was du heute miterlebt hast?",
    "Wenn du einen eigenen Künstleratelier haben könntest, was würdest du erschaffen?",
    "Was ist dein Lieblings-Gesellschaftsspiel?",
    "Welcher Moment hat dich inspiriert?",
    "Was ist das Mutigste, was du für einen Freund getan hast?",
    "Wenn du einen eigenen Koch-Workshop geben könntest, was würdest du kochen?",
    "Was ist dein Lieblings-Rätselspiel?",
    "Welche Hoffnung trägst du für die Zukunft?",
    "Was ist das Großherzigste, was du getan hast?",
    "Wenn du einen eigenen Tanzstudio haben könntest, welche Stile würdest du unterrichten?",
    "Was ist dein Lieblings-Strategiespiel?",
    "Welcher Moment war ein Wendepunkt in deinem Leben?",
    "Was ist das Schönste, was du heute zu jemandem gesagt hast?",
    "Wenn du einen eigenen Kunstworkshop anbieten könntest, was würdest du lehren?",
    "Was ist dein Lieblings-Partyspiel für große Gruppen?",
    "Welche Erkenntnis hat deine Sichtweise verändert?",
    "Was ist das Beste an diesem Moment?",
    "Wenn du einen eigenen Traumworkshop halten könntest, was würdest du lehren?",
    "Was ist deine liebste Art, neue Leute kennenzulernen?",
    "Welche positive Veränderung hast du in letzter Zeit an dir bemerkt?",
    "Was ist eine kleine Sache, die deinen Tag heute schon besser gemacht hat?",
    
    # ===== NEUE FRAGEN - POSITIV & KREATIV =====
    "Welches Geräusch beruhigt dich sofort?",
    "Was war als Kind deine liebste Süßigkeit?",
    "Wenn du eine Superkraft haben könntest, die nur Gutes bewirkt, welche wäre es?",
    "Welche Farbe verbindest du mit Glück?",
    "An welchen fiktiven Ort aus einem Buch oder Film würdest du gerne reisen?",
    "Was ist eine kleine Sache, die dir heute ein Lächeln ins Gesicht gezaubert hat?",
    "Welches Lied aus deiner Jugend hörst du heute noch gerne?",
    "Wenn du mit einem Tier sprechen könntest, welches wäre es und worüber würdet ihr reden?",
    "Was ist dein liebstes Märchen?",
    "Beschreibe deinen perfekten, gemütlichen Abend.",
    "Welchen Duft verbindest du mit einer schönen Erinnerung? (z.B. frisch gemähtes Gras, Plätzchen im Ofen)",
    "Was war dein Lieblingsspielzeug als Kind?",
    "Berge oder Meer: Wo fühlst du dich wohler?",
    "Welches Fabelwesen fändest du als Haustier am besten?",
    "Welche Jahreszeit magst du am liebsten und warum?",
    "Was ist eine Fähigkeit, die du gerne lernen würdest, nur zum Spaß? (z.B. Jonglieren, ein Instrument)",
    "Welchen fiktiven Charakter hättest du gerne als besten Freund?",
    "Was ist dein liebstes 'Wohlfühlessen' (Comfort Food)?",
    "Wenn du einen Tag in einem Jahrzehnt deiner Wahl verbringen könntest, welches wäre es?",
    "Welches Wort in der deutschen Sprache findest du besonders schön?",
    "Was sammelst du oder hast du früher gesammelt?",
    "Welches Muster magst du am liebsten? (z.B. Punkte, Streifen, Karos)",
    "Wenn dein Leben ein Filmgenre wäre, welches wäre es heute? (Komödie, Abenteuer, etc.)",
    "Was ist die schönste Wolkenform, die du je gesehen hast?",
    "Welches Kinderlied fällt dir spontan ein?",
    "Tee, Kaffee oder Kakao? Was ist dein Lieblings-Heißgetränk?",
    "Welches Kompliment, das du mal bekommen hast, ist dir in Erinnerung geblieben?",
    "Wenn du eine neue Eissorte erfinden könntest, wie würde sie heißen und schmecken?",
    "Was ist ein Hobby, das du als Kind hattest?",
    "Welcher kleine Alltagsmoment gibt dir Kraft?",
    "Wenn du deinem jüngeren Ich einen aufmunternden Satz sagen könntest, welcher wäre das?",
    "Welches Buch hast du als Kind immer wieder gelesen?",
    "Welchen Baum findest du am schönsten?",
    "Was ist ein Klang aus der Natur, den du liebst? (z.B. Regenprasseln, Vogelgezwitscher)",
    "Wenn du ein eigenes, kleines Café eröffnen würdest, wie würde es heißen?",
    "Was war die lustigste Fernsehwerbung, an die du dich aus deiner Kindheit erinnerst?",
    "Welche drei Dinge würdest du auf eine einsame Insel mitnehmen (nur zum Vergnügen)?",
    "Welchen Trickfilm-Charakter mochtest du als Kind am liebsten?",
    "Was ist deine liebste Art, einen freien Tag zu verbringen?",
    "Welches Brettspiel oder Kartenspiel hast du früher gerne gespielt?",
    "Wenn du dir eine Fantasie-Haarfarbe aussuchen könntest, welche wäre es?",
    "Was ist eine positive Eigenschaft, die du an dir magst?",
    "Welcher Geruch erinnert dich an den Herbst?",
    "Wenn du ein Instrument wärst, welches wärst du?",
    "Was war dein liebstes Schulfach, bei dem es nicht um Leistung ging?",
    "Welchen positiven Gedanken möchtest du heute mit der Community teilen?",
    "Wenn du eine Blume wärst, welche wärst du?",
    "Welcher Film schafft es immer wieder, dich aufzuheitern?",
    "Was ist das Schönste daran, aus dem Fenster zu schauen?",
    "Welchen Namen würdest du einem kleinen, flauschigen Roboter geben, der dir im Haushalt hilft?",
    "Was ist dein Lieblings-Sternbild oder Himmelskörper?",
    "Wenn du für einen Tag unsichtbar wärst, welchen netten Streich würdest du spielen?",
    "Welches Gefühl verbindest du mit dem Wort 'Zuhause'?",
    "Was ist dein liebstes Obst?",
    "An welchen Traum kannst du dich erinnern, der dich zum Lächeln gebracht hat?",
    "Wenn du ein magisches Portal in deinem Kleiderschrank hättest, wohin würde es führen?",
    "Was war das schönste Geschenk, das du je selbst gemacht hast?",
    "Welches Geräusch verbindest du mit dem Sommer?",
    "Was ist eine kleine, freundliche Geste, die dir viel bedeutet?",
    "Wenn du ein Haus auf einem Baum bauen könntest, wie sähe es aus?",
    "Was ist deine liebste mythologische Gestalt?",
    "Welches Wort beschreibt dein aktuelles Gefühl auf positive Weise?",
    "Wenn du die Welt in einer einzigen Farbe malen könntest, welche wäre das heute?",
    "Was ist ein schönes Zitat, das dich inspiriert?",
    "Welches Tier findest du am majestätischsten?",
    "Wenn du ein Wetterphänomen wärst, welches wärst du? (z.B. sanfter Regen, Sonnenschein)",
    "Was war das beste Versteck beim Versteckspielen als Kind?",
    "Welches Gemüse magst du am liebsten?",
    "Wenn du einem Gefühl eine Farbe zuordnen müsstest, welche Farbe hätte die Gelassenheit?",
    "Was ist ein schöner Ort in deiner Nähe, den du gerne besuchst?",
    "Welcher Song hat den besten Gute-Laune-Rhythmus?",
    "Wenn du ein eigenes Fantasieland erfinden könntest, was wäre seine Besonderheit?",
    "Was ist eine Sache, die du heute nur für dich tust?",
    "Welche Kinderserie hatte das beste Intro-Lied?",
    "Frühaufsteher oder Nachteule?",
    "Welches Kleidungsstück aus deiner Vergangenheit hättest du gerne wieder?",
    "Wenn du dir eine Fähigkeit aus einem Videospiel aussuchen könntest, welche wäre es?",
    "Was ist das beruhigendste, was du heute gesehen hast?",
    "Wenn du ein Buch schreiben würdest, wie würde der erste Satz lauten?",
    "Welches Küchengerät findest du am faszinierendsten?",
    "Was ist dein Lieblings-Wochentag und warum?",
    "Wenn du einen Tag lang die Rolle mit einem Tier tauschen könntest, welches wäre es?",
    "Was ist ein schönes deutsches Sprichwort oder eine Redewendung?",
    "Welches Verkehrsmittel findest du am entspannendsten? (z.B. Zug, Fahrrad)",
    "Was ist eine kleine Tradition, die du genießt?",
    "Welches Kunstwerk (Gemälde, Skulptur) beeindruckt dich?",
    "Wenn du einen Schutzpatron für kleine Alltagsfreuden ernennen könntest, wer oder was wäre das?",
    "Was ist das lustigste Wort, das du kennst?",
    "Welchen Geruch verbindest du mit dem Winter?",
    "Wenn du einen eigenen Planeten gestalten könntest, welche Farbe hätte der Himmel?",
    "Was ist ein einfacher Tipp, um sich sofort ein bisschen besser zu fühlen?",
    "Welches historische Gebäude findest du am schönsten?",
    "Wenn du ein Gewürz wärst, welches wärst du?",
    "Was ist eine schöne Erinnerung an einen Ausflug in deiner Kindheit?",
    "Welches Naturwunder möchtest du unbedingt einmal sehen?",
    "Wenn du eine Wolke benennen könntest, welchen Namen gäbest du ihr?",
    "Was ist dein Lieblings-Snack für einen Filmabend?",
    "Welches Geräusch macht dich nostalgisch?",
    "Wenn du eine neue, freundliche Geste erfinden könntest, wie sähe sie aus?",
    "Teile ein Bild oder eine Beschreibung von etwas Schönem, das du heute gesehen hast.",
    "Welchen Tee trinkst du am liebsten zur Entspannung?",
    "Was ist ein lustiger Fakt, den du kürzlich gelernt hast?",
    "Wenn du ein Geheimbund-Mitglied wärst, was wäre euer (positiver) Auftrag?",
    "Welches Muster in der Natur findest du am faszinierendsten? (z.B. Schneeflocken, Spinnennetze)",
    "Was war deine Lieblings-Pausenbeschäftigung in der Schule?",
    "Wenn du ein Boot hättest, wie würdest du es taufen?",
    "Welches Gefühl gibt dir ein klarer Sternenhimmel?",
    "Was ist das gemütlichste Möbelstück, das du dir vorstellen kannst?",
    "Welches Tier hat das niedlichste Baby?",
    "Wenn du eine offizielle Hymne für den Montag schreiben müsstest, wie würde sie klingen?",
    "Welches ist dein liebstes Geräusch beim Kochen? (z.B. Zwiebeln brutzeln)",
    "Was ist eine Sache, auf die du dich dieses Wochenende freust?",
    "Welcher Held aus deiner Kindheit (real oder fiktiv) hat dich inspiriert?",
    "Wenn du eine Brücke bauen würdest, was würde sie verbinden?",
    "Welches ist das schönste Wort für 'Liebe' in einer anderen Sprache, das du kennst?",
    "Beschreibe deinen Traum-Lesesessel.",
    "Was ist eine kleine Sache, für die du heute dankbar bist?",
    "Welches Kinder-Frühstücksflocken-Maskottchen war das beste?",
    "Wenn du einen Tag lang ein Geist wärst, was würdest du Gutes tun?",
    "Was ist das befriedigendste Gefühl? (z.B. eine Schutzfolie abziehen)",
    "Welche Form hat deine Lieblingstasse?",
    "Wenn du dir einen Titel für deine Lebensgeschichte ausdenken müsstest, welcher wäre es?",
    "Welcher Duft erinnert dich an Frühling?",
    "Was ist eine einfache Freude, die man nicht kaufen kann?",
    "Welches Fabelwesen würdest du am liebsten mal treffen?",
    "Was ist das lustigste Tiergeräusch?",
    "Wenn du eine Zeitkapsel für dich selbst in einem Jahr packen würdest, was käme hinein?",
    "Welches ist dein liebstes Gefühl auf der Haut? (z.B. Sonnenstrahlen, weicher Stoff)",
    "Was ist ein schönes Ritual vor dem Schlafengehen?",
    "Welcher Disney-Song zaubert dir sofort gute Laune?",
    "Wenn du ein Element wärst (Feuer, Wasser, Erde, Luft), welches würdest du wählen?",
    "Was ist die schönste Pflanze, die du je gesehen hast?",
    "Welches ist das beste Geräusch am Morgen?",
    "Wenn du eine Nachricht in einer Flaschenpost senden würdest, was stünde darin?",
    "Was ist dein liebstes Wolken-Beobachtungs-Motiv?",
    "Welches ist das beste Gefühl nach einem langen Spaziergang?",
    "Wenn du ein eigenes Festival organisieren könntest, was wäre das Motto?",
    "Welcher Duft von Essen macht dich sofort hungrig?",
    "Was ist ein lustiger Versprecher, an den du dich erinnerst?",
    "Wenn du eine Farbe hören könntest, wie würde 'Gelb' klingen?",
    "Was ist dein liebster Ort, um in Ruhe nachzudenken?",
    "Welches ist dein Lieblings-Kuchen oder -Gebäck?",
    "Wenn du einen Roboter-Sidekick hättest, welche Persönlichkeit hätte er?",
    "Was ist das schönste Geräusch in einer Bibliothek?",
    "Welches ist das beste an einem Regentag?",
    "Wenn du eine neue Art von Blume züchten könntest, wie sähe sie aus?",
    "Welches ist dein liebster 'dummer Witz'?",
    "Was ist ein Film, den du unzählige Male sehen könntest?",
    "Wenn du der Titel eines Liedes wärst, welcher wäre das?",
    "Welches Kompliment gibst du selbst gerne anderen?",
    "Welches ist dein liebstes Pausenbrot aus der Kindheit?",
    "Wenn du einen Tag in einem Studio Ghibli Film leben könntest, welcher wäre es?",
    "Was ist ein Geräusch, das dich an Gemütlichkeit erinnert? (z.B. strickende Nadeln, ein schnurrender Kater)",
    "Welchen fiktiven Gegenstand aus einem Film oder Buch hättest du gerne?",
    "Was ist das Beste daran, barfuß zu laufen?",
    "Wenn du ein eigenes, kleines Museum eröffnen könntest, was würdest du ausstellen?",
    "Welches Wort bringt dich immer zum Schmunzeln?",
    "Beschreibe das perfekte Picknick.",
    "Welches Tier wäre der beste Tänzer?",
    "Was ist eine positive Angewohnheit, die du gerne hättest?",
    "Wenn du eine Wolkenbotschaft an die Welt senden könntest, was stünde darin?",
    "Welches ist das schönste Geräusch im Wald?",
    "Was war das coolste Baumhaus, das du je gesehen oder dir vorgestellt hast?",
    "Wenn du ein Gericht wärst, welche Zutat wäre deine geheime Zutat?",
    "Welches ist dein Lieblings-Schlafanzug-Material?",
    "Was ist eine schöne Erinnerung an einen Wintertag als Kind?",
    "Wenn deine Socken sprechen könnten, was würden sie über dich erzählen?",
    "Welches ist das beste Gefühl beim Aufwachen?",
    "Was ist dein Lieblings-Kräuterduft? (z.B. Lavendel, Minze)",
    "Wenn du ein Piratenkapitän wärst, wie würde dein (freundliches) Piratenschiff heißen?",
    "Welches Wetter passt am besten zu deiner aktuellen Stimmung?",
    "Was ist eine kleine, nette Geste, die du heute für jemanden tun könntest?",
    "Welcher Charakter aus einem Kinderbuch wärst du gerne?",
    "Was ist das Faszinierendste an Sternen?",
    "Wenn du einen eigenen Feiertag erfinden würdest, was würde man an diesem Tag feiern?",
    "Welches Gefühl vermittelt dir der Anblick von Seifenblasen?",
    "Was ist dein Lieblings-Suppengemüse?",
    "Wenn du eine geheime, magische Tür in deinem Zimmer hättest, wohin würde sie führen?",
    "Welches Tier hat den lustigsten Gang?",
    "Was ist eine kleine Sache, die du gut kannst und auf die du stolz bist?",
    "Wenn du ein Muster stricken oder häkeln würdest, welches wäre es?",
    "Welcher ist der beste Platz im Kino?",
    "Was ist eine schöne Erinnerung an eine Übernachtungsparty bei Freunden?",
    "Wenn du die Farbe des Meeres ändern könntest, welche Farbe hätte es?",
    "Welches ist dein liebstes Geräusch beim Backen?",
    "Was ist ein Hobby, das du gerne mal ausprobieren würdest?",
    "Wenn du eine Figur in einem Märchen wärst, wärst du der Held, der lustige Sidekick oder das weise, alte Tier?",
    "Welches ist das schönste an einem Sonnenaufgang?",
    "Was ist dein liebstes Kartoffelgericht?",
    "Wenn du einen Leuchtturm für einen Tag betreiben könntest, was wäre das Beste daran?",
    "Welches ist dein Lieblings-Klanginstrument zur Entspannung?",
    "Was ist eine freundliche Sache, die du vor Kurzem für dich selbst getan hast?",
    "Wenn du einen Drachen als Haustier hättest, was wäre seine besondere Fähigkeit?",
    "Welches ist dein liebstes 'altmodisches' Wort?",
    "Was ist eine schöne Erinnerung an den Sportunterricht in der Schule?",
    "Wenn du ein Geist wärst, in welchem alten Schloss würdest du am liebsten (freundlich) spuken?",
    "Was ist das beruhigendste Muster zum Anschauen?",
    "Welches ist dein Lieblings-Pancake- oder Waffel-Topping?",
    "Wenn du eine Statue entwerfen würdest, wen oder was würde sie ehren?",
    "Teile ein Bild oder eine Beschreibung deiner Lieblingstasse.",
    "Welches ist dein Lieblingsgeruch nach einem Sommerregen?",
    "Wenn du ein magisches Wesen wärst, das Pflanzen wachsen lässt, was wäre deine Spezialität?",
    "Was ist die lustigste Form, die du je in einer Kartoffel oder einem Gemüse gesehen hast?",
    "Welches Lied kannst du von Anfang bis Ende mitsingen?",
    "Wenn du eine geheime Zutat für Glück hättest, was wäre das?",
    "Welches ist dein liebstes Gefühl von Stoff auf der Haut? (z.B. Leinen, Fleece)",
    "Was ist eine kleine, positive Nachricht, die du heute gerne hören würdest?",
    "Wenn du ein Entdecker wärst, was würdest du am liebsten entdecken? (Eine neue Insel, eine neue Pflanzenart...)",
    "Welches ist das schönste an einem Sonnenuntergang?",
    "Was ist dein liebstes Ritual am Morgen?",
    "Wenn du ein Pokémon wärst, welches wärst du?",
    "Welches ist das beste Geräusch, um einzuschlafen?",
    "Was ist eine Fähigkeit, die du an fiktiven Charakteren bewunderst?",
    "Wenn du eine Wolke wärst, wohin würdest du am liebsten reisen?",
    "Was ist das leckerste, was du je gebacken hast?",
    "Welches ist dein Lieblingszitat aus einem Kinderfilm?",
    "Wenn du eine Nachricht an Außerirdische senden könntest, was wäre die freundliche Botschaft?",
    "Was ist das entspannendste Wassergeräusch? (Wellen, Bachplätschern, Regen)",
    "Welchen Namen würdest du einem sehr kleinen, sehr flauschigen Tier geben?",
    "Was ist ein schöner Brauch aus einer anderen Kultur, den du magst?",
    "Wenn du ein eigenes Sternbild am Himmel kreieren könntest, wie sähe es aus und wie würde es heißen?",
    "Welches ist dein liebstes Gefühl von Wärme? (Sonne, Kamin, Decke)",
    "Was ist eine kleine Sache, über die du dich zuletzt gefreut hast wie ein Kind?",
    "Wenn du ein Superhelden-Cape hättest, welche Farbe hätte es?",
    "Was ist das beste am Herbstlaub?",
    "Welches Brettspiel weckt bei dir schöne Erinnerungen?",
    "Wenn du eine neue Geschmacksrichtung für Tee erfinden könntest, welche wäre das?",
    "Was ist das lustigste Missverständnis, das du je erlebt hast?",
    "Welches ist dein Lieblings-Naturmaterial? (Holz, Stein, Wolle...)",
    "Wenn du ein magisches Amulett hättest, welche kleine, positive Kraft würde es dir verleihen?",
    "Was ist eine schöne Erinnerung an einen Besuch im Zoo oder Tierpark?",
    "Welches ist dein liebster Duft im Badezimmer? (Seife, Shampoo...)",
    "Wenn du ein Mosaik gestalten würdest, was wäre das Motiv?",
    "Was ist das Schönste an einem handgeschriebenen Brief?",
    "Welches Tier hat die beeindruckendsten Augen?",
    "Wenn du der Kurator einer 'Galerie der kleinen Freuden' wärst, was wäre das erste Ausstellungsstück?",
    "Was ist dein liebstes Frühstück an einem freien Tag?",
    "Welches Wort klingt wie eine Umarmung?",
    "Wenn du ein Labyrinth entwerfen würdest, was wäre in der Mitte zu finden?",
    "Was ist eine kleine Geste der Selbstfürsorge, die du heute praktizierst?",
    "Welches ist dein Lieblings-Muster auf Kleidung?",
    "Wenn du ein Charakter in einem Videospiel wärst, was wäre dein Inventar?",
    "Was ist das schönste Geräusch in einer Stadt?",
    "Welches ist dein liebstes Märchenschloss?",
    "Wenn du einen freundlichen Waldgeist treffen würdest, was würdest du ihn fragen?",
    "Was ist eine kleine Sache, die dein Zimmer gemütlicher macht?",
    "Welches ist dein Lieblings-Soundeffekt aus einem alten Cartoon?",
    "Wenn du eine Eisskulptur erschaffen könntest, was würde sie darstellen?",
    "Was ist das beste am Sterne-Beobachten?",
    "Welches Kompliment hast du zuletzt jemandem gemacht?",
    "Wenn du eine Seifenblase wärst, wohin würdest du fliegen?",
    "Welches Tier wäre der beste Geschichtenerzähler?",
    "Was ist dein liebstes Gefühl von Kühle an einem heißen Tag? (z.B. kalte Fliesen unter den Füßen)",
    "Wenn du ein eigenes, kleines Boot hättest, wohin würde deine erste Reise gehen?",
    "Was ist das lustigste Tier-Video, das du je gesehen hast?",
    "Welches ist dein Lieblings-Schulheft-Gekritzel von früher?",
    "Wenn du eine neue, positive Tradition für den Jahreswechsel erfinden könntest, welche wäre das?",
    "Was ist das schönste am Geräusch von Wind in den Bäumen?",
    "Welches ist dein Lieblings-Gewürz?",
    "Wenn du ein Zaubertrank-Brauer wärst, welcher Trank wäre deine Spezialität? (z.B. ein Trank für süße Träume)",
    "Was ist eine schöne Erinnerung an eine Fahrradtour?",
    "Welches ist dein Lieblings-Wort, um 'gemütlich' zu beschreiben?",
    "Wenn du ein Musikinstrument erfinden könntest, wie würde es klingen?",
    "Was ist das beste an frisch gewaschener Bettwäsche?",
    "Welches Fabelwesen hätte den besten Modegeschmack?",
    "Wenn du ein Haus am Strand hättest, welche Farbe hätte die Eingangstür?",
    "Was ist eine kleine Sache, die du heute gelernt hast?",
    "Welches ist dein Lieblings-Sandwich?",
    "Wenn du einen Tag lang mit den Wolken sprechen könntest, was würdest du sie fragen?",
    "Was ist das befriedigendste Küchengeräusch?",
    "Welches ist dein Lieblings-Dinosaurier?",
    "Wenn du eine Geheimsprache erfinden würdest, auf welchem Prinzip würde sie basieren?",
    "Was ist das schönste am Fliegen (im Flugzeug oder in Gedanken)?",
    "Welches ist dein Lieblings-Kinderspiel für draußen? (z.B. Gummitwist, Himmel und Hölle)",
    "Wenn du ein Gemälde wärst, in welchem Museum würdest du gerne hängen?",
    "Was ist ein kleiner Moment des Friedens in deinem Alltag?",
    "Welches ist dein liebstes 'Regenwetter-Essen'?",
    "Wenn du eine freundliche Botschaft auf den Mond schreiben könntest, die jeder sehen kann, was stünde da?",
    "Was ist das beste an einer Tasse Tee oder Kaffee am Morgen?",
    "Welches Tier wäre der beste Zuhörer?",
    "Wenn du ein Lesezeichen wärst, in welchem Buch würdest du gerne stecken?",
    "Was ist dein liebster Duft in einem Wald?",
    "Welches ist dein liebstes historisches Zeitalter, rein ästhetisch betrachtet?",
    "Wenn du ein Planet in unserem Sonnensystem wärst, welcher wäre es und warum?",
    "Was ist eine schöne Erinnerung, die mit Musik verbunden ist?",
    "Welches ist dein Lieblings-Müsli-Zusatz?",
    "Wenn du ein magisches Artefakt finden würdest, was würde es tun?",
    "Was ist das beste Geräusch am Meer?",
    "Welchen Namen würdest du einem kleinen, freundlichen Roboter geben?",
    "Was ist eine kleine, positive Veränderung, die du heute bemerkt hast?",
    "Wenn du eine Brücke aus Regenbogen bauen könntest, wohin würde sie führen?",
    "Welches ist dein Lieblings-Gemüse zum Knabbern?",
    "Was ist eine schöne Erinnerung an einen Geburtstag als Kind?",
    "Wenn du ein eigenes Café benennen müsstest, welcher Name wäre es?",
    "Welches ist das lustigste Tier, das du kennst?",
    "Was ist eine kleine Sache, die du kaum erwarten kannst?",
    "Wenn du ein Puzzleteil wärst, welches Motiv würdest du am liebsten mitgestalten?",
    "Was ist das beste am Geruch von altem Papier in Büchern?",
    "Welches ist dein Lieblings-Wort für Lachen?",
    "Teile eine positive Affirmation oder einen Gedanken für den Tag.",
    "Wenn du ein eigenes Schiff bauen würdest, was wäre die Galionsfigur?",
    "Was ist das entspannendste Geräusch, das ein Tier macht?",
    "Welchen einfachen Snack hast du als Kind geliebt?",
    "Wenn du einen Tag lang die Hauptfigur in einem Märchen wärst, welches wäre es?",
    "Was ist das Schönste an einem handgemachten Geschenk?",
    "Welches Wort beschreibt am besten das Gefühl von warmer Sonne auf der Haut?",
    "Wenn du eine neue Blume entdecken würdest, wie würde sie heißen?",
    "Was ist dein liebster Ort, um den Himmel zu beobachten?",
    "Welches Kinderlied steckt dir manchmal als Ohrwurm fest?",
    "Wenn du ein Muster aus Sternen an den Nachthimmel malen könntest, was wäre es?",
    "Was ist das beste an einem freien Nachmittag ohne Pläne?",
    "Welches Tier wäre der beste Kuschelpartner?",
    "Wenn du einen Tag lang in einem Baumhaus leben könntest, was würdest du tun?",
    "Was ist ein kleiner Luxus, den du dir manchmal gönnst?",
    "Welchen Duft verbindest du mit Weihnachten oder der Winterzeit?",
    "Wenn du ein Hüter eines magischen Gartens wärst, was würde dort wachsen?",
    "Was ist dein liebstes 'Wort des Tages' gewesen?",
    "Welches Gefühl gibt dir ein altes Fotoalbum?",
    "Wenn du eine neue Art von Wolke erfinden könntest, wie sähe sie aus?",
    "Was ist eine kleine Sache, die du an deiner Stadt oder deinem Dorf magst?",
    "Welches mythische Wesen fändest du am interessantesten zu treffen?",
    "Wenn du ein eigenes Eis am Stiel kreieren könntest, welche Form und welchen Geschmack hätte es?",
    "Was ist das beruhigendste Licht? (Kerzenlicht, Lichterketten...)",
    "Welches Tier würdest du gerne mal in freier Wildbahn sehen?",
    "Wenn du einen Soundtrack für dein Leben zusammenstellen würdest, welcher Song wäre der Opener?",
    "Was ist dein liebstes Ritual, um einen Tag ausklingen zu lassen?",
    "Welches Spielzeug aus deiner Kindheit vermisst du manchmal?",
    "Wenn du eine Insel nach einem Gefühl benennen müsstest, wie würde sie heißen?",
    "Was ist das Schönste daran, jemandem eine Freude zu machen?",
    "Welches ist dein liebstes Geräusch in der Küche?",
    "Wenn du ein Buch über Freundlichkeit schreiben würdest, was stünde auf dem Cover?",
    "Was ist dein Lieblings-Baumaterial für eine Sandburg?",
    "Welches Tier hat das schönste Fell- oder Federmuster?",
    "Wenn du einen Tag lang ein Vogel wärst, wohin würdest du fliegen?",
    "Was ist das beste am Geruch von frisch gebackenem Brot?",
    "Welches Kinderbuch sollte jeder Erwachsene noch einmal lesen?",
    "Wenn du eine eigene, geheime Hütte im Wald hättest, was wäre das Besondere daran?",
    "Was ist eine kleine, positive Sache, die du dir für morgen vorgenommen hast?",
    "Welches ist dein Lieblings-Wort für 'schön'?",
    "Wenn du ein magisches Musikinstrument hättest, was würde es bewirken, wenn du spielst?",
    "Was ist das beste an einem Nickerchen?",
    "Welches Tier wäre der beste Briefzusteller?",
    "Wenn du einen eigenen Tee mischen würdest, welche Zutaten wären drin?",
    "Was ist eine schöne Erinnerung an einen Schulausflug?",
    "Welches Wetter lässt dich kreativ werden?",
    "Wenn du ein eigenes, kleines Lädchen eröffnen würdest, was würdest du verkaufen?",
    "Was ist das befriedigendste Gefühl beim Gärtnern?",
    "Welches ist dein Lieblings-Animationsfilm?",
    "Wenn du ein eigenes Sprichwort erfinden müsstest, wie würde es lauten?",
    "Was ist eine kleine, freundliche Tat, die du heute beobachtet hast?",
    "Welches ist dein Lieblingsplatz in deinem Zuhause?",
    "Wenn du ein magisches Gewürz hättest, welchen Geschmack würde es jedem Essen verleihen?",
    "Was ist das beste am Geräusch von knisterndem Feuer?",
    "Welches ist dein Lieblings-Outfit für einen gemütlichen Tag?",
    "Wenn du ein freundliches Schlossgespenst wärst, wie würdest du die Bewohner zum Lachen bringen?",
    "Was ist eine kleine Sache, auf die du dich in der nächsten Jahreszeit freust?",
    "Welches ist dein Lieblings-Gefühl, wenn du müde ins Bett fällst?",
    "Wenn du eine geheime Zutat für einen 'Gute-Laune-Kuchen' hättest, was wäre es?",
    "Was ist das schönste an einem klaren Nachthimmel?",
    "Welches Tier verkörpert für dich Gelassenheit?",
    "Wenn du eine Zeitkapsel mit schönen Erinnerungen füllen würdest, was wäre die erste?",
    "Was ist ein kleiner, alltäglicher Sieg?",
    "Welches Geräusch verbindest du mit Geborgenheit?",
    "Wenn du die letzte Seite eines Buches schreiben könntest, wie würde der letzte Satz lauten?",
    "Was ist ein positiver Gedanke oder ein Wunsch, den du für die Community für das kommende Jahr hast?"
]

async def seed_questions():
    """Verbindet sich mit der DB und fügt die Fragen aus der Liste hinzu."""
    load_dotenv()
    conn = None
    try:
        log_database_action("Starting FdT questions seeding", "fdt_questions")
        conn = await get_db_connection()
        log_success("Successfully connected to database. Starting seeding...")
        
        inserted_count = 0
        for question_text in FDT_QUESTIONS_LIST:
            exists = await conn.fetchrow("SELECT 1 FROM fdt_questions WHERE question_text = $1", question_text)
            if not exists:
                await conn.execute("INSERT INTO fdt_questions (question_text) VALUES ($1)", question_text)
                inserted_count += 1
                if inserted_count % 10 == 0:
                    log_database_action(f"Progress: {inserted_count} questions inserted", "fdt_questions")
        
        total_questions = await conn.fetchval("SELECT COUNT(*) FROM fdt_questions")
        log_success(f"Seeding completed! {inserted_count} new questions added. Total: {total_questions}")

    except Exception as e:
        log_error("FdT seeding failed", str(e))
    finally:
        if conn:
            await conn.close()
            log_database_action("Database connection closed", "CONNECTION")

if __name__ == "__main__":
    print("🌱 Starting FdT Questions Seeding...")
    asyncio.run(seed_questions())
    print("✅ Seeding completed!")
